# Generated by Django 5.2.5 on 2025-08-29 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('total_votes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='polls_poll_is_acti_5cfcc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('vote_count', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_id', models.CharField(db_index=True, max_length=255)),
                ('voted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.option')),
            ],
            options={
                'ordering': ['-voted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['poll', 'vote_count'], name='polls_optio_poll_id_782f62_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter_id', 'voted_at'], name='polls_vote_voter_i_32804f_idx'),
        ),
    ]
